name: Update BLT Hash

on:
  push:
    branches:
      - master
      - release/*
      - autoupdate
        
jobs:
  update-hash:
    runs-on: ubuntu-latest
    env:
      IDENT: wolfhud                        #Identifier for the mod.
      BRANCH.DL: master                     #Branch hosting the stable release version.
      BRANCH.UPD: autoupdate                #Branch hosting the meta.json and SuperBLT_Hasher.py files.
      CHANGELOG: autoupdate/Changelog.md    #Branch + Filename for the Changelog-File.
    steps:
    - name: Checkout Mod Branch
      uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH.DL }}
        path: "./${{ env.BRANCH.DL }}/"
    - name: Checkout Updater Branch
      uses: actions/checkout@v2
      with:
        ref: ${{ env.BRANCH.UPD }}
        token: ${{ secrets.GITHUB_TOKEN }}
        path: "./${{ env.BRANCH.UPD }}/"
    - name: Setup Python
      uses: actions/setup-python@v1.1.1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Calculate Hash
      run: |
        hash = python $GITHUB_WORKSPACE/$env.BRANCH.UPD/SuperBLT_Hasher.py $GITHUB_WORKSPACE/$BRANCH.DL/
        echo ::set-env name=HASH::$hash
    - name: Create local changes
      run: |
        cat <<EOM >$GITHUB_WORKSPACE/$env.BRANCH.UPD/meta.json
        [
            {
                "ident": "$IDENT",
                "hash": "$HASH",
                "download": "https://github.com/$GITHUB_REPOSITORY/archive/$env.BRANCH.DL.zip",
                "patchnotes": "https://github.com/$GITHUB_REPOSITORY/blob/$env.CHANGELOG"
            }
        ]
        EOM
    - name: Commit files
      run: |
        cd $GITHUB_WORKSPACE/$env.BRANCH.UPD/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Change Hash for new Version." -a
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH.UPD }}
        directory: ${{ GITHUB_WORKSPACE }}/${{ env.BRANCH.UPD }}/