name: Update BLT Hash

on:
  push:
    branches:
      - master
      - release/*
      - autoupdate
        
jobs:
  update-hash:
    runs-on: ubuntu-latest
    env:
      IDENT: wolfhud                        #Identifier for the mod.
      BRANCH_DL: master                     #Branch hosting the stable release version.
      BRANCH_UPD: autoupdate                #Branch hosting the meta.json and SuperBLT_Hasher.py files.
      CHANGELOG: autoupdate/Changelog.md    #Branch + Filename for the Changelog-File.
    steps:
    - name: Checkout Mod Branch
      uses: actions/checkout@v2
      with:
        ref: master
        path: "./master/"
    - name: Checkout Updater Branch
      uses: actions/checkout@v2
      with:
        ref: autoupdate
        token: ${{ github.token }}
        path: "./autoupdate/"
    - name: Setup Python
      uses: actions/setup-python@v1.1.1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Calculate Hash
      id: hash
      run: |
        echo ::set-env name=HASH::$(python $GITHUB_WORKSPACE/$BRANCH_UPD/SuperBLT_Hasher.py $GITHUB_WORKSPACE/$BRANCH_DL/)
    - name: Create local changes
      run: |
        cat <<EOM >$GITHUB_WORKSPACE/$BRANCH_UPD/meta.json
        [
            {
                "ident": "$IDENT",
                "hash": "$HASH",
                "download": "https://github.com/$GITHUB_REPOSITORY/archive/$BRANCH_DL.zip",
                "patchnotes": "https://github.com/$GITHUB_REPOSITORY/blob/$CHANGELOG"
            }
        ]
        EOM
    - name: Commit files
      run: |
        cd $GITHUB_WORKSPACE/$BRANCH_UPD/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Change Hash for new Version." -a
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ github.token }}
        branch: autoupdate
        directory: ${{ github.workspace }}/autoupdate/